# AuthBugDemo
Demo to reproduce a `bug` that occurs when `context.Fail` is called within the authorization handler.
